/********************************************
* This is a configuration file generated by 
* Processor Expert for the Keyboard module.
********************************************/

#ifndef _KEYBOARD_CONFIG_H_
#define _KEYBOARD_CONFIG_H_

#ifndef gKeyBoardSupported_d
#define gKeyBoardSupported_d        1
#endif
#ifndef gKBD_KeysCount_c
#define gKBD_KeysCount_c            4
#endif
#ifndef gKeyEventNotificationMode_d
#define gKeyEventNotificationMode_d gKbdEventShortLongPressMode_c
#endif

#endif //_KEYBOARD_CONFIG_H_
