/********************************************
* This is a configuration file generated by 
* Processor Expert for the TimersManager module.
********************************************/

#ifndef _TIMERSMANAGER_CONFIG_H_
#define _TIMERSMANAGER_CONFIG_H_

#ifndef gTMR_Enabled_d
#define gTMR_Enabled_d                     1
#endif
#ifndef gTimestamp_Enabled_d
#define gTimestamp_Enabled_d               1
#endif
#ifndef gTMR_PIT_Timestamp_Enabled_d
#define gTMR_PIT_Timestamp_Enabled_d       0
#endif
#ifndef gTMR_PIT_FreqMultipleOfMHZ_d
#define gTMR_PIT_FreqMultipleOfMHZ_d       1
#endif
#ifndef gTMR_EnableLowPowerTimers_d
#define gTMR_EnableLowPowerTimers_d        1
#endif
#ifndef gTMR_EnableHWLowPowerTimers_d
#define gTMR_EnableHWLowPowerTimers_d      0
#endif
#ifndef gTMR_EnableMinutesSecondsTimers_d
#define gTMR_EnableMinutesSecondsTimers_d  1
#endif
#ifndef gTmrApplicationTimers_c
#define gTmrApplicationTimers_c            4
#endif
#ifndef gTmrStackTimers_c
#define gTmrStackTimers_c                  3
#endif
#ifndef gTmrTaskStackSize_c
#define gTmrTaskStackSize_c                500
#endif
#ifndef gTmrTaskPriority_c
#define gTmrTaskPriority_c                 2
#endif

#endif /* _TIMERSMANAGER_CONFIG_H_ */
