/********************************************
* This is a configuration file generated by 
* Processor Expert for the NVM module.
********************************************/

#ifndef _NVM_CONFIG_H_
#define _NVM_CONFIG_H_

#ifndef gNvStorageIncluded_d
#define gNvStorageIncluded_d          0
#endif
#ifndef gNvUseFlexNVM_d
#define gNvUseFlexNVM_d               0
#endif
#ifndef gNvFragmentation_Enabled_d
#define gNvFragmentation_Enabled_d    0
#endif
#ifndef gNvUseExtendedFeatureSet_d
#define gNvUseExtendedFeatureSet_d    0
#endif
#ifndef gNvTableEntriesCountMax_c
#define gNvTableEntriesCountMax_c     32
#endif
#ifndef gNvRecordsCopiedBufferSize_c
#define gNvRecordsCopiedBufferSize_c  64
#endif
#ifndef gNvCacheBufferSize_c
#define gNvCacheBufferSize_c          64
#endif
#ifndef gNvMinimumTicksBetweenSaves_c
#define gNvMinimumTicksBetweenSaves_c 4
#endif
#ifndef gNvCountsBetweenSaves_c
#define gNvCountsBetweenSaves_c       256
#endif
#ifndef gNvFormatRetryCount_c
#define gNvFormatRetryCount_c         3
#endif
#ifndef gNvPendigSavesQueueSize_c
#define gNvPendigSavesQueueSize_c     32
#endif
#ifndef gNvEnableCriticalSection_c
#define gNvEnableCriticalSection_c      1
#endif

#endif //_NVM_CONFIG_H_
