/********************************************
* This is a configuration file generated by 
* Processor Expert for the LPM module.
********************************************/

#ifndef _LPM_CONFIG_H_
#define _LPM_CONFIG_H_

#ifndef cPWR_LVD_Enable
#define cPWR_LVD_Enable                        0
#endif
#ifndef cPWR_LVD_Ticks
#define cPWR_LVD_Ticks                         60
#endif
#ifndef cPWR_UsePowerDownMode
#define cPWR_UsePowerDownMode                  1
#endif
#ifndef gPWR_EnsureOscStabilized_d
#define gPWR_EnsureOscStabilized_d             0
#endif
#ifndef cPWR_DeepSleepMode
#define cPWR_DeepSleepMode                     10
#endif
#ifndef cPWR_SleepMode
#define cPWR_SleepMode                         1
#endif
#ifndef cPWR_LPTMRTickTimeSource_ERCLK32K
#define cPWR_LPTMRTickTimeSource_ERCLK32K      cLPTMR_PRS_1000ms
#endif
#ifndef cPWR_TMRTicks
#define cPWR_TMRTicks                          3
#endif
#ifndef cPWR_DeepSleepDurationMs
#define cPWR_DeepSleepDurationMs               3000
#endif
#ifndef cPWR_CallWakeupStackProcAfterDeepSleep
#define cPWR_CallWakeupStackProcAfterDeepSleep 0
#endif

#endif //_LPM_CONFIG_H_
