/********************************************
* This is a configuration file generated by 
* Processor Expert for the SecLib module.
********************************************/

#ifndef _SECLIB_CONFIG_H_
#define _SECLIB_CONFIG_H_

#ifndef gSecLib_HWSupport_d
#define gSecLib_HWSupport_d gSecLib_NoHWSupport_d
#endif

#endif //_SECLIB_CONFIG_H_
