/********************************************
* This is a configuration file generated by 
* Processor Expert for the MAC module.
********************************************/

#ifndef _MAC_CONFIG_H_
#define _MAC_CONFIG_H_

#ifndef gMacInstancesCnt_c
#define gMacInstancesCnt_c  1
#endif

#ifndef gMacTaskStackSize_c
#define gMacTaskStackSize_c 1024
#endif

#ifndef gMacTaskPriority_c
#define gMacTaskPriority_c  1
#endif

#endif //_MAC_CONFIG_H_
