/********************************************
* This is a configuration file generated by 
* Processor Expert for the PHY module.
********************************************/

#ifndef _PHY_CONFIG_H_
#define _PHY_CONFIG_H_

#ifndef gAspCapability_d
#define gAspCapability_d    1
#endif

#ifndef gMaxPhyTimers_c
#define gMaxPhyTimers_c     10
#endif

#ifndef gMpmMaxPANs_c
#define gMpmMaxPANs_c       1
#endif

#ifndef gPhyInstancesCnt_c
#define gPhyInstancesCnt_c  1
#endif

#ifndef gPhyTaskStackSize_c
#define gPhyTaskStackSize_c 600
#endif

#ifndef gPhyTaskPriority_c
#define gPhyTaskPriority_c  OSA_PRIORITY_REAL_TIME
#endif

#ifndef gAfcEnabled_d
#define gAfcEnabled_d		0
#endif

#endif //_PHY_CONFIG_H_
