/********************************************
* This is a configuration file generated by 
* Processor Expert for the FSCI module.
********************************************/

#ifndef _FSCI_CONFIG_H_
#define _FSCI_CONFIG_H_

#ifndef gFsciIncluded_c
#define gFsciIncluded_c         1
#endif
#ifndef gFsciMaxOpGroups_c
#define gFsciMaxOpGroups_c      8
#endif
#ifndef gFsciMaxInterfaces_c
#define gFsciMaxInterfaces_c    1
#endif
#ifndef gFsciMaxPayloadLen_c
#define gFsciMaxPayloadLen_c    245
#endif
#ifndef gFsciUseFmtLog_c
#define gFsciUseFmtLog_c        0
#endif
#ifndef gFsciUseFileDataLog_c
#define gFsciUseFileDataLog_c   0
#endif
#ifndef gFsciLoggingInterface_c
#define gFsciLoggingInterface_c 1
#endif

#endif //_FSCI_CONFIG_H_
