/***********************************************
* This is a configuration file generated by 
* Processor Expert for the OSAbstraction module.
***********************************************/

#ifndef _FSL_OSA_EXT_CONFIG_H_
#define _FSL_OSA_EXT_CONFIG_H_

#ifndef osNumberOfSemaphores
#define osNumberOfSemaphores 0
#endif
#ifndef osNumberOfMutexes
#define osNumberOfMutexes    1
#endif
#ifndef osNumberOfTimers
#define osNumberOfTimers     0
#endif
#ifndef osNumberOfMessageQs
#define osNumberOfMessageQs  0
#endif
#ifndef osNumberOfMessages
#define osNumberOfMessages   0
#endif
#ifndef osNumberOfEvents
#define osNumberOfEvents     1
#endif

#ifndef gMainThreadStackSize_c
#define gMainThreadStackSize_c 1024
#endif
#ifndef gMainThreadPriority_c
#define gMainThreadPriority_c OSA_PRIORITY_IDLE
#endif

#endif /* _FSL_OSA_EXT_CONFIG_H_ */
